### ISSUE TITLE
Replace network overview table

### ISSUE THREAD

**Issue by palango** [raiden-network/status-page#32]
Replace the table with a more in detail view in given token networks.

It's better to replace it with a more detailed view of the network. This could include:
- Number of open/closed/settled channels
- Number of participants
- Average number of channels per participant
- Channels with biggest deposits
- Participants with most channels
- Avg. deposit per channel
- Avg. deposit per participant

**Comment by kelsos** [comment]
I was looking into the deposit averages and I I am guessing, that the values returned are in the minimum denomination. So for `RTT` this would be `1e-8` and for other tokens it would be `1e-18`. It would not make any senses to create averages from these values. I would probably need the decimal value of the deposit or the number of decimals in order to calculate the proper average.

**Comment by kelsos** [comment]
I was wondering, a channel's `deposit` is the sum of the deposits of `participant1` and `participant2` right?
